### ISSUE TITLE
For the training procedure.

### ISSUE THREAD

**Issue by bigfeetsmalltone** [sangmin-git/LMC-Memory#12]
I set the short_len = 5, and an error occurred as follows:
![image](https://user-images.githubusercontent.com/30223491/139587093-ecba01d8-52cf-41b1-9cde-c27960b59821.png)
the image size is 128*128

**Comment by bigfeetsmalltone** [comment]
if I set the short_len= 10, it can work.

**Comment by sangmin-git** [comment]
This is because the memory encoder (`motion_matching_encoder`) contains temporal pooling.
There can be two options.
1. set `short_len` to 8 or more.
2. modify the pooling part (`nn.MaxPool3d`) of `motion_matching_encoder` 

Thanks!

**Comment by bigfeetsmalltone** [comment]
Very thanks, the issue has been solved.

**Comment by xiximin** [comment]
Hello, how do you convert datasets into jpg images? Can you provide a link to download the dataset?
