### ISSUE TITLE
questions on training

### ISSUE THREAD

**Issue by yuyudiandian** [sangmin-git/LMC-Memory#3]
Thank you for this good job！But when i run train.py,the following errors happened.
![image](https://user-images.githubusercontent.com/71555221/124249735-bd07af80-db56-11eb-90ae-041a512374d9.png)
It seems some dimensions didn't match. I try to modify the model.py ,
![image](https://user-images.githubusercontent.com/71555221/124250270-4c14c780-db57-11eb-8451-7855a0bea605.png)
but this errors still happen, can you give me some advice? 
![image](https://user-images.githubusercontent.com/71555221/124250346-6353b500-db57-11eb-96de-8760f5b22b3c.png)

**Comment by sangmin-git** [comment]
I think you used a different dataset than Moving-MNIST or KTH.
I assume that used dataset has img_size 28 which is not divided by 16 in memory encoder.
I recommend resizing the input to 32. (results are not guaranteed)
