### ISSUE TITLE
Question about the test code

### ISSUE THREAD

**Issue by hujb48** [sangmin-git/LMC-Memory#5]
Hi, It is a great work, I would like to implementation model and firstly I want to test the kth video to see the prediction. 
**Here, I use the command with the pre-trained model like:**
`python test --dataset kth --make_frame True --test_data_dir ./kth/test --test_result_dir ./kth/test_out/video_00039 --checkpoint_load_file ./checkpoints/trained_file_kth.pt --img_size 128 --img_channel 1 --memory_size 100 --short_len 10 --out_len 40 --batch_size 8` 
**to test kth/walking/person10_walking_d4_uncomp.avi pocessed into single frames which has been put into  "video_00039" directory which contains 544 frames. however, it has a mistake when I run the above command**
`Traceback (most recent call last):
  File "C:/code/pose_generation/LMC-Memory-main/test.py", line 87, in <module>
    out_pred = pred_model(short_data, None, args.out_len, phase=2)`
 ` File "C:\ProgramData\Anaconda3\envs\LMC\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)`
 ` File "C:\ProgramData\Anaconda3\envs\LMC\lib\site-packages\torch\nn\parallel\data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])`
 ` File "C:\ProgramData\Anaconda3\envs\LMC\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)`
`  File "C:\code\pose_generation\LMC-Memory-main\model.py", line 79, in forward
    h[layer_i], c[layer_i] = self.convlstm_list[layer_i](input_x, h[layer_i], c[layer_i])`
 ` File "C:\ProgramData\Anaconda3\envs\LMC\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)`
 ` File "C:\code\pose_generation\LMC-Memory-main\convlstm.py", line 20, in forward
    it = torch.sigmoid(xi+hi)`
`RuntimeError: The size of tensor a (30) must match the size of tensor b (28) at non-singleton dimension 2`
`Process finished with exit code 1
`
**And this is my dir's architecture:**
kth
├── test
│   ├── video_00039
│   │   ├── frame_00000.jpg
...
│   │   ├── frame_00543.jpg
├── test_out
│   ├── video_00039
checkpoints
├── trained_file_kth.pt

**by debug command, it would be showed that xi is a tensor with the shape [8,128,30,40], while hi is a tensor with another shape [8,128,28,40]. In all, how can I deal with this mistake, and why this mistake could happen?**

Hope you can reply me at your convenience,
Yours, Hu.

**Comment by sangmin-git** [comment]
I think you did not resize the video frames.
Each frame should be resized to 128*128.

Thanks!

**Comment by hujb48** [comment]
thanks a lot, it works, and by the way, what type is your training GPU? I try to train a model with the size of 256*256 in RTX3070, which takes a "CUDA out of memory" error, and I try to use the small batch size, and it doesn't work, how should I do? Thanks again for your prompt reply!

**Comment by sangmin-git** [comment]
We used the machine with 8*TITAN RTX. The larger the frame size, the vastly more GPU memory is needed. Therefore, it is recommended to resize the frame size reasonably. However, still, the RTX3070 seems to be not enough...

**Comment by hujb48** [comment]
Thx for ur reply!
