### ISSUE TITLE
about the training time 

### ISSUE THREAD

**Issue by MartinYue** [sangmin-git/LMC-Memory#8]
hi, thanks for your great job. I'd like to know how long does it take to train your model? does it cost lots of time (or gpus)? thank you!

**Comment by sangmin-git** [comment]
In case of using 4*TITAN RTX gpus, it takes about 7days to train the model.

Thanks!

**Comment by huyi1998** [comment]
> In case of using 4*TITAN RTX gpus, it takes about 7days to train the model.
> 
> Thanks!

7days？which dataset to train for 7days？
