### ISSUE TITLE
LPIPS evaluation

### ISSUE THREAD

**Issue by Pixie8888** [sangmin-git/LMC-Memory#9]
Hi,
Thanks for releasing code! I have a question about the LPIPS evaluation. Do we need normalise image before sending it into LPIPS model? It seems you normalise the image to [0,1], but in the official LPIPS code, the image is normalised to [-1,1]. Will it affect evaluation?
![image](https://user-images.githubusercontent.com/72333326/137132286-e18457d8-d752-4aa3-986b-c2e35dcdd36b.png)

**Comment by sangmin-git** [comment]
We knew the issue, but we followed the implementation of Conv-TT-LSTM (Neurips20) for fair comparisons.
The tendency of LPIPS metric is maintained. (The lower the better quality)
